### PR TITLE
Fix GC reconnect failing after app restart, update protbufs and readme

### PR DESCRIPTION
**Pull request by sapphyrus**
I ran into the issue that my client didn't reconnect properly after losing connection to steam and then reconnecting, for example, due to steam going down. steam-user connects fine and I then properly quit the app and restart it.
I'm pretty sure that I've narrowed down the issue here:

in `appLaunched` you require `_isInCSGO` to be false in order to do anything:
https://github.com/DoctorMcKay/node-globaloffensive/blob/bb31382fe772071467ddc252e99517d01107d411/index.js#L55-L66

but you never set it to false in `appQuit`:
https://github.com/DoctorMcKay/node-globaloffensive/blob/bb31382fe772071467ddc252e99517d01107d411/index.js#L81-L89

### CODE REVIEW

**Comment by DoctorMcKay** [comment]
Looks good, but can you move this to `handleAppQuit`?

**Comment by sapphyrus** [comment]
> Looks good, but can you move this to `handleAppQuit`?

done, should've done it like that in the first place

**Comment by sapphyrus** [comment]
Updated protobufs since Valve changed a bunch of things, this change lets people read the Wingman and Danger Zone ranks, player level and XP, new inspectItem props

**Comment by DoctorMcKay** [comment]
Looks good! Did you test all these changes?

**Comment by sapphyrus** [comment]
The `_isInCSGO` fix works and I'm actively using my fork in a bot that uses `requestPlayersProfile` and the `playersProfile` event, so these definitely work.
But I don't think anything was broken by the protobufs update, all I did was grab the newest protos from https://github.com/SteamDatabase/GameTracking-CSGO/tree/master/Protobufs then ran `npm run generate-protos`.

**Comment by DoctorMcKay** [comment]
Thanks a bunch, I'll get this pushed out shortly.

**Pull request merged**
