### PR TITLE
New method requestGame

### PR DESCRIPTION
**Pull request by Yaroslav-95**
Added a new method to request full info about a finished match.

### CODE REVIEW

**Comment by Yaroslav-95** [comment]
Hi! I hope I am not being pushy, but it would be really useful to me to have this in your package (i.e. not having to create a forked npm package). If there is any change that needs to be done before merging to upstream, please let me know!

**Comment by Yaroslav-95** [comment]
If anyone else needs to use this method, you can alternately install my fork https://www.npmjs.com/package/@yaroslav-95/globaloffensive

**Comment by AlexTolmachev** [comment]
@DoctorMcKay Why there is no feedback on this PR? I would really like to see this method in the library. Maybe I can help somehow?

**Comment by DoctorMcKay** [comment]
Sorry for the very long delay. I've added it in 2.2.0.

**Pull request closed without merging**
